easy_admin:
    site_name: 'Guestbook Tutorial'
    user:
        display_name: true
        display_avatar: false
    entities:
        # List the entity class name you want to manage
        Conference:
            class: App\Entity\Conference
            list:
                title: "List of Conferences"
        Comment:
            class: App\Entity\Comment
            form:
                fields:
                    - author
#        - App\Entity\User
